# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmyroom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_image',
            field=models.ImageField(null=True, upload_to=b''),
        ),
    ]
