# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmyroom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room_booking',
            name='in_time',
            field=models.TimeField(blank=True, choices=[(b'12:30 am', b'00:30'), (b'01:00 am', b'01:00'), (b'01:30 am', b'01:30'), (b'02:00 am', b'02:00'), (b'02:30 am', b'02:30'), (b'03:00 am', b'03:00'), (b'12:30 am', b'03:30'), (b'02:00 am', b'04:00'), (b'12:30 am', b'04:30'), (b'12:30 am', b'05:30'), (b'12:30 am', b'06:30'), (b'12:30 am', b'07:30'), (b'12:30 am', b'08:30'), (b'12:30 am', b'09:30'), (b'12:30 am', b'10:30'), (b'12:30 am', b'11:30'), (b'12:30 am', b'12:30'), (b'12:30 am', b'13:30'), (b'12:30 am', b'14:30'), (b'12:30 am', b'15:30'), (b'12:30 am', b'16:30'), (b'12:30 am', b'17:30'), (b'12:30 am', b'18:30'), (b'12:30 am', b'19:30'), (b'12:30 am', b'20:30'), (b'12:30 am', b'21:30'), (b'12:30 am', b'22:30'), (b'12:30 am', b'23:30'), (b'12:30 am', b'24:30')], default=b'17:30'),
        ),
        migrations.AlterField(
            model_name='room_booking',
            name='out_time',
            field=models.TimeField(blank=True, choices=[(b'12:30 am', b'00:30'), (b'01:00 am', b'01:00'), (b'01:30 am', b'01:30'), (b'02:00 am', b'02:00'), (b'02:30 am', b'02:30'), (b'03:00 am', b'03:00'), (b'12:30 am', b'03:30'), (b'02:00 am', b'04:00'), (b'12:30 am', b'04:30'), (b'12:30 am', b'05:30'), (b'12:30 am', b'06:30'), (b'12:30 am', b'07:30'), (b'12:30 am', b'08:30'), (b'12:30 am', b'09:30'), (b'12:30 am', b'10:30'), (b'12:30 am', b'11:30'), (b'12:30 am', b'12:30'), (b'12:30 am', b'13:30'), (b'12:30 am', b'14:30'), (b'12:30 am', b'15:30'), (b'12:30 am', b'16:30'), (b'12:30 am', b'17:30'), (b'12:30 am', b'18:30'), (b'12:30 am', b'19:30'), (b'12:30 am', b'20:30'), (b'12:30 am', b'21:30'), (b'12:30 am', b'22:30'), (b'12:30 am', b'23:30'), (b'12:30 am', b'24:30')], default=b'17:30'),
        ),
    ]
