# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmyroom', '0003_auto_20161027_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room_booking',
            name='in_time',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='room_booking',
            name='out_time',
            field=models.TimeField(blank=True),
        ),
    ]
