# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 04:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmyroom', '0005_auto_20161027_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room_booking',
            name='in_time',
            field=models.TimeField(blank=True, choices=[(datetime.time(0, 0), '12:00 am'), (datetime.time(0, 30), '12:30 am'), (datetime.time(1, 0), '1:00 am'), (datetime.time(1, 30), '1:30 am'), (datetime.time(2, 0), '2:00 am'), (datetime.time(2, 30), '2:30 am'), (datetime.time(3, 0), '3:00 am'), (datetime.time(3, 30), '3:30 am'), (datetime.time(4, 0), '4:00 am'), (datetime.time(4, 30), '4:30 am'), (datetime.time(5, 0), '5:00 am'), (datetime.time(5, 30), '5:30 am'), (datetime.time(6, 0), '6:00 am'), (datetime.time(6, 30), '6:30 am'), (datetime.time(7, 0), '7:00 am'), (datetime.time(7, 30), '7:30 am'), (datetime.time(8, 0), '8:00 am'), (datetime.time(8, 30), '8:30 am'), (datetime.time(9, 0), '9:00 am'), (datetime.time(9, 30), '9:30 am'), (datetime.time(10, 0), '10:00 am'), (datetime.time(10, 30), '10:30 am'), (datetime.time(11, 0), '11:00 am'), (datetime.time(11, 30), '11:30 am'), (datetime.time(12, 0), '12:00 pm'), (datetime.time(12, 30), '12:30 pm'), (datetime.time(13, 0), '1:00 pm'), (datetime.time(13, 30), '1:30 pm'), (datetime.time(14, 0), '2:00 pm'), (datetime.time(14, 30), '2:30 pm'), (datetime.time(15, 0), '3:00 pm'), (datetime.time(15, 30), '3:30 pm'), (datetime.time(16, 0), '4:00 pm'), (datetime.time(16, 30), '4:30 pm'), (datetime.time(17, 0), '5:00 pm'), (datetime.time(17, 30), '5:30 pm'), (datetime.time(18, 0), '6:00 pm'), (datetime.time(18, 30), '6:30 pm'), (datetime.time(19, 0), '7:00 pm'), (datetime.time(19, 30), '7:30 pm'), (datetime.time(20, 0), '8:00 pm'), (datetime.time(20, 30), '8:30 pm'), (datetime.time(21, 0), '9:00 pm'), (datetime.time(21, 30), '9:30 pm'), (datetime.time(22, 0), '10:00 pm'), (datetime.time(22, 30), '10:30 pm'), (datetime.time(23, 0), '11:00 pm'), (datetime.time(23, 30), '11:30 pm')], default=b'17:30'),
        ),
        migrations.AlterField(
            model_name='room_booking',
            name='out_time',
            field=models.TimeField(blank=True, choices=[(datetime.time(0, 0), '12:00 am'), (datetime.time(0, 30), '12:30 am'), (datetime.time(1, 0), '1:00 am'), (datetime.time(1, 30), '1:30 am'), (datetime.time(2, 0), '2:00 am'), (datetime.time(2, 30), '2:30 am'), (datetime.time(3, 0), '3:00 am'), (datetime.time(3, 30), '3:30 am'), (datetime.time(4, 0), '4:00 am'), (datetime.time(4, 30), '4:30 am'), (datetime.time(5, 0), '5:00 am'), (datetime.time(5, 30), '5:30 am'), (datetime.time(6, 0), '6:00 am'), (datetime.time(6, 30), '6:30 am'), (datetime.time(7, 0), '7:00 am'), (datetime.time(7, 30), '7:30 am'), (datetime.time(8, 0), '8:00 am'), (datetime.time(8, 30), '8:30 am'), (datetime.time(9, 0), '9:00 am'), (datetime.time(9, 30), '9:30 am'), (datetime.time(10, 0), '10:00 am'), (datetime.time(10, 30), '10:30 am'), (datetime.time(11, 0), '11:00 am'), (datetime.time(11, 30), '11:30 am'), (datetime.time(12, 0), '12:00 pm'), (datetime.time(12, 30), '12:30 pm'), (datetime.time(13, 0), '1:00 pm'), (datetime.time(13, 30), '1:30 pm'), (datetime.time(14, 0), '2:00 pm'), (datetime.time(14, 30), '2:30 pm'), (datetime.time(15, 0), '3:00 pm'), (datetime.time(15, 30), '3:30 pm'), (datetime.time(16, 0), '4:00 pm'), (datetime.time(16, 30), '4:30 pm'), (datetime.time(17, 0), '5:00 pm'), (datetime.time(17, 30), '5:30 pm'), (datetime.time(18, 0), '6:00 pm'), (datetime.time(18, 30), '6:30 pm'), (datetime.time(19, 0), '7:00 pm'), (datetime.time(19, 30), '7:30 pm'), (datetime.time(20, 0), '8:00 pm'), (datetime.time(20, 30), '8:30 pm'), (datetime.time(21, 0), '9:00 pm'), (datetime.time(21, 30), '9:30 pm'), (datetime.time(22, 0), '10:00 pm'), (datetime.time(22, 30), '10:30 pm'), (datetime.time(23, 0), '11:00 pm'), (datetime.time(23, 30), '11:30 pm')], default=b'17:30'),
        ),
    ]
